USER_PIN_CONFIG:
  PIN_MODE:
    map_tbl: NA
    bit_width: 0
    PA:
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    PB:
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Output
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    PC:
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Alt.
    - Input
    - Alt.
    - Alt.
    - NA
    - NA
    - Alt.
    - Alt.
    PD:
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    PE:
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    PF:
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Alt.
    - Alt.
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    PG:
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Input
    - Alt.
    - NA
    - NA
    - NA
    - NA
    - NA
  OUTPUT_TYPE:
    map_tbl: NA
    bit_width: 0
    PA:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    PB:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    PC:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - NA
    - NA
    - Push-Pull
    - Push-Pull
    PD:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    PE:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    PF:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    PG:
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - Push-Pull
    - NA
    - NA
    - NA
    - NA
    - NA
  PULL_UP_DOWN:
    map_tbl:
      NA: -2
      Disable: 0
      Pull-Up: 2
      Pull-Down: 3
    bit_width: 2
    PA:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PB:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PC:
    - Pull-Up
    - Pull-Up
    - Disable
    - Pull-Up
    - Pull-Up
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Pull-Up
    - Pull-Up
    - NA
    - NA
    - Disable
    - Disable
    PD:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PE:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PF:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PG:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - NA
    - NA
    - NA
  OUTPUT_DATA:
    map_tbl:
      NA: -2
      Low: 0
      High: 1
    bit_width: 1
    PA:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PB:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - High
    - Low
    - Low
    - Low
    - Low
    PC:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - Low
    - Low
    PD:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PE:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PF:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PG:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - NA
    - NA
    - NA
  OUTPUT_SET_BIT:
    map_tbl:
      NA: -2
      Low: 0
      High: 1
    bit_width: 1
    PA:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PB:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - High
    - Low
    - Low
    - Low
    - Low
    PC:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - Low
    - Low
    PD:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PE:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PF:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PG:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - NA
    - NA
    - NA
  OUTPUT_CLEAR_BIT:
    map_tbl:
      NA: -2
      Low: 0
      High: 1
    bit_width: 1
    PA:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PB:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PC:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - Low
    - Low
    PD:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PE:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PF:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    PG:
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - Low
    - NA
    - NA
    - NA
    - NA
    - NA
  INTERRUPT_MODE:
    map_tbl:
      NA: -2
      Disable: 0
      Level-NonPendingMode: 1
      Level-PendingMode: 2
      Edge: 3
    bit_width: 2
    PA:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PB:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PC:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Edge
    - Disable
    - Disable
    - NA
    - NA
    - Disable
    - Disable
    PD:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PE:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PF:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PG:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - NA
    - NA
    - NA
  INTERRUPT_TRIGGER:
    map_tbl:
      NA: -2
      Disable: 0
      Low Level/Falling Edge: 1
      High Level/Rising Edge: 2
      Both Edge: 3
    bit_width: 2
    PA:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PB:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PC:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Both Edge
    - Disable
    - Disable
    - NA
    - NA
    - Disable
    - Disable
    PD:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PE:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PF:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PG:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - NA
    - NA
    - NA
  DEBOUNCING_FILTER:
    map_tbl:
      NA: -2
      Disable: 0
      Enable: 1
    bit_width: 1
    PA:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PB:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PC:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Enable
    - Disable
    - Disable
    - NA
    - NA
    - Disable
    - Disable
    PD:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PE:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PF:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PG:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - NA
    - NA
    - NA
  DEBOUNCING_CLK_SRC:
    map_tbl:
      NA: -2
      LSI: 0
      LSE: 1
      MCLK: 4
      HSI: 5
      HSE: 6
      PLL: 7
    bit_width: 3
    GROUP0:
      port_list:
      - PA
      - PB
      clock_source: MCLK
    GROUP1:
      port_list:
      - PC
      - PD
      clock_source: MCLK
    GROUP2:
      port_list:
      - PE
      - PF
      - PG
      clock_source: LSI
  DEBOUNCING_CLK_DIVIDER:
    map_tbl: FUNC:range(0,256)
    bit_width: 8
    GROUP0:
      port_list:
      - PA
      - PB
      clock_divider: 0
    GROUP1:
      port_list:
      - PC
      - PD
      clock_divider: 0
    GROUP2:
      port_list:
      - PE
      - PF
      - PG
      clock_divider: 0
  PORT_OUTPUT_STRENGTH:
    map_tbl:
      NA: -2
      Disable: 0
      Enable: 1
    bit_width: 1
    PA:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PB:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PC:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - Disable
    - Disable
    PD:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PE:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PF:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    PG:
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - Disable
    - NA
    - NA
    - NA
    - NA
    - NA
