USER_ADC_CONFIG:
  ADC_ID_2:
    ADC_MODE_e: ADC_MODE_SINGLE
    ADC_TRG_SRC_e: ADC_TRG_SRC_ADST
    ADC_SEQ_CNT: 0
    ADC_TRG_TYPE_e: ADC_TRG_TYPE_INDEPENDENT
    ADC_SEQ_0:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_1:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_2:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_3:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_4:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_5:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_6:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_SEQ_7:
      ADC_TRG_SRC_e: ADC_TRG_SRC_NONE
    ADC_CMP: false
    ADC_CLK_e: ADC_CLK_PCLK
    ADC_CLK_PCLK:
      ADC_PCLK_DIV: 2
    ADC_OPS_e: ADC_OPS_POLL
