USER_UART_CONFIG:
  UART_ID_0:
    UART_BAUDRATE: 115200
    UART_DATA_e: UART_DATA_8
    UART_PARITY_e: UART_PARITY_NONE
    UART_STOP_e: UART_STOP_1
    UART_CLK_e: UART_CLK_MCCR
    UART_CLK_MCCR:
      UART_CLK_MCCR_e: UART_CLK_MCCR_MCLK
      UART_MCCR_DIV: 1
    UART_OPS_e: UART_OPS_POLL
